bitmap:
  color_space: RGB
  generate_axis: XY
  generate_type: blks
  particle_name: minecraft:end_rod
  path: sample.png
  reversed_axis: false
fast_copy_func: true
func_namespace: mcdi
midi:
  auto_adjust:
    base: '20'
    is_enabled: true
    step: '0.1'
    tolerance: '2.0'
  auto_func: true
  blank_ticks: '0.0'
  frontend: soma.Soma
  generate_type: ig
  middles: {}
  note_links: true
  overrides:
    gvol: false
    phase: false
    pitch: false
    program: false
  path: sample.mid
  pitch_factor: '1.0'
  plugins:
    title.MainTitle:
      '#plugin-cfg-title-MainTitle-in_subtitle': IN_SUBTITLE
      '#plugin-cfg-title-MainTitle-in_title': IN_TITLE
      '#plugin-cfg-title-MainTitle-out_subtitle': OUT_SUBTITLE
      '#plugin-cfg-title-MainTitle-out_title': OUT_TITLE
  tick_rate: '20'
  tick_scale: '1.0'
  use_func: false
  volume_factor: '1.0'
  wrap_length: '128'
minecraft_path: D:\Minecraft\.minecraft
shared_home: false
version_selected: fabric-loader-0.9.2+build.206-1.16.2
world_selected: MCDI
